<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sasd.HealthNotebook.Application\Sasd.HealthNotebook.Application.csproj" />
    <ProjectReference Include="..\Sasd.HealthNotebook.Domain\Sasd.HealthNotebook.Domain.csproj" />
    <ProjectReference Include="..\Sasd.HealthNotebook.Infrastructure\Sasd.HealthNotebook.Infrastructure.csproj" />
  </ItemGroup>
</Project>
