<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sasd.HealthNotebook.Application\Sasd.HealthNotebook.Application.csproj" />
    <ProjectReference Include="..\Sasd.HealthNotebook.Domain\Sasd.HealthNotebook.Domain.csproj" />
  </ItemGroup>
</Project>
